#
# Copyright 2017 - 2019 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
#      http://www.boost.org/LICENSE_1_0.txt)
#
# This is loosely derived from my work in boost-ci
# at https://github.com/boostorg/boost-ci
#
#
dist: xenial
language: cpp

addons:
  apt:
    packages:
      - binutils-gold
      - gdb
      - libc6-dbg
        
branches:
  only:
    - develop
    - master
    
#
# Default toolsets in Ubuntu
#
#       trusty xenial bionic
#        14.04  16.04  18.04
#       ------ ------ ------
# clang    3.4    3.8    6.0
#   gcc  4.8.2  5.3.1  7.3.0
#

anchors:
  clang-5:  &clang-5  { apt: { packages: [ "clang-5.0",
                                           "libstdc++-7-dev" ], sources: [ "llvm-toolchain-xenial-5.0",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  clang-6:  &clang-6  { apt: { packages: [ "clang-6.0",
                                           "libc6-dbg",
                                           "libc++-dev",
                                           "libstdc++-8-dev" ], sources: [ "llvm-toolchain-xenial-6.0",
                                                                           "ubuntu-toolchain-r-test"   ] } }
  gcc-7:    &gcc-7    { apt: { packages: [ "g++-7"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }
  gcc-8:    &gcc-8    { apt: { packages: [ "g++-8"           ], sources: [ "ubuntu-toolchain-r-test"   ] } }

script:
  - ci/travis/build.sh

jobs:
  allow_failures:
    - env:
      - COPY="all the environment settings from your job"

  include:
    - os: linux
      addons: *clang-5
      env:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_CXX_COMPILER=clang++

    - os: linux
      addons: *clang-6
      env:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_CXX_COMPILER=clang++

    - os: linux
      addons: *gcc-8
      env:
        - COMMENT=codecov
        - CMAKE_BUILD_TYPE=Debug
        - CMAKE_CXX_COMPILER=g++-8
        - CMAKE_CXX_FLAGS=--coverage
      script:
        - pushd /tmp && git clone https://github.com/linux-test-project/lcov.git && export PATH=/tmp/lcov/bin:$PATH && which lcov && lcov --version && popd
        - ci/travis/codecov.sh

    - os: linux
      addons: *gcc-8
      env:
        - COMMENT=ubsan
        - CMAKE_BUILD_TYPE=Debug
        - CMAKE_CXX_COMPILER=g++-8
        - CMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined"
        - CMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
        - UBSAN_OPTIONS=print_stacktrace=1

    - os: linux
      addons: *gcc-7
      env:
        - COMMENT=valgrind
        - CMAKE_BUILD_TYPE=Debug
        - CMAKE_CXX_COMPILER=g++-7
      script:
        - ci/travis/valgrind.sh

notifications:
  email:
    false
